name: 'Quack'
description:
  'Check version diff between repository and registry and cry like a duck!'
author: 'Dockcenter'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'tag'
  color: 'blue'

# Define your inputs here.
inputs:
  source:
    description: The URL or the id of the source to check version diff
    required: true
  source-parser:
    description:
      The parser to get version information from the source. Be default, it will
      choose the appropriate parser based on source.
    required: true
    default: auto
  source-parser-options:
    description:
      Additional parser options in key value string format (e.g.
      `key1=value1,key2=value2`)
  destination:
    description: The URL or the id of the destination to check version diff
    required: true
  destination-parser:
    description:
      The parser to get version information from the destination. Be default, it
      will choose the appropriate parser based on destination.
    required: true
    default: auto
  destination-parser-options:
    description:
      Additional parser options in key value string format (e.g.
      `key1=value1,key2=value2`)

# Define your outputs here.
outputs:
  diff-add:
    description:
      A string list containing all versions that exist in source but not in
      destination
  diff-delete:
    description:
      A string list containing all versions that exist in destination but not in
      source

runs:
  using: node20
  main: dist/index.js
